"""Urls for the emencia.django.newsletter statistics"""
from django.conf.urls.defaults import *

urlpatterns = patterns('emencia.django.newsletter.views.statistics',
                       url(r'^(?P<slug>[-\w]+)/$',
                           'view_newsletter_statistics',
                           name='newsletter_newsletter_statistics'),
                       url(r'^(?P<slug>[-\w]+)/(?P<mailing_list_pk>[0-9]+)/$',
                           'view_newsletter_statistics',
                           name='newsletter_newsletter_statistics_mailing_list'),
                       url(r'^report/(?P<slug>[-\w]+)/$',
                           'view_newsletter_report',
                           name='newsletter_newsletter_report'),
                       url(r'^report/(?P<slug>[-\w]+)/(?P<mailing_list_pk>[0-9]+)/$',
                           'view_newsletter_report',
                           name='newsletter_newsletter_report_mailing_list'),
                       url(r'^charts/(?P<slug>[-\w]+)/$',
                           'view_newsletter_charts',
                           name='newsletter_newsletter_charts'),
                       url(r'^charts/(?P<slug>[-\w]+)/(?P<mailing_list_pk>[0-9]+)/$',
                           'view_newsletter_charts',
                           name='newsletter_newsletter_charts_mailing_list'),
                       url(r'^density/(?P<slug>[-\w]+)/$',
                           'view_newsletter_density',
                           name='newsletter_newsletter_density'),
                       url(r'^density/(?P<slug>[-\w]+)/(?P<mailing_list_pk>[0-9]+)/$',
                           'view_newsletter_density',
                           name='newsletter_newsletter_density_mailing_list'),
                       )

